AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda + API Gateway using SAM

Resources:
  PlaylistAPI:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: PlaylistAPI

# Read Playlist
  ReadPlaylistFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ReadPlaylistFunction
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: Read/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tune_out
      Events:
        ApiForMyApp:
          Type: HttpApi
          Properties:
            Path: /readPlaylist
            Method: GET
            ApiId: !Ref PlaylistAPI

# Delete Playlist
DeletePlaylistFunction:
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: DeletePlaylistFunction
    Handler: index.handler
    Runtime: nodejs22.x
    CodeUri: Delete/
    Policies:
      - DynamoDBCrudPolicy:
          TableName: tune_out
    Events:
      ApiForMyApp:
        Type: HttpApi
        Properties:
          Path: /deletePlaylist
          Method: DELETE
          ApiId: !Ref PlaylistAPI

Outputs:
  ApiUrl:
    Description: "HTTP API endpoint base URL"
    Value: !Sub "https://${PlaylistAPI}.execute-api.${AWS::Region}.amazonaws.com"


    #Create Playlist
    CreatePlaylistFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CreatePlaylistFunction
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: CreatePlaylist/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tune_out
      Events:
        ApiForMyApp:
          Type: HttpApi
          Properties:
            Path: /CreatePlaylist
            Method: POST
            ApiId: !Ref PlaylistAPI

Outputs:
  ApiUrl:
    Description: "HTTP API endpoint base URL"
    Value: !Sub "https://${PlaylistAPI}.execute-api.${AWS::Region}.amazonaws.com"


# Update Playlist
UpdatePlaylistFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: UpdatePlaylistFunction
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: UpdatePlaylist/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tune_out
      Events:
        ApiForMyApp:
          Type: HttpApi
          Properties:
            Path: /UpdatePlaylist
            Method: POST
            ApiId: !Ref PlaylistApi

Outputs:
  ApiUrl:
    Description: "HTTP API endpoint base URL"
    Value: !Sub "https://${MyNamedHttpApi}.execute-api.${AWS::Region}.amazonaws.com"